tickers_schealth = ['QNCX', 'GOSS', 'TCMD', 'BDTX', 'AXGN', 'BBIO', 'AUPH', 'RCUS',
                   'SKIN', 'ATRI', 'SRDX', 'NVRO', 'AMTI', 'ADPT', 'CYRX', 'ADUS',
                   'BCRX', 'ZYXI', 'HSKA', 'ANIK', 'VNDA', 'AMPH', 'EGRX', 'EAR',
                   'MLAB', 'ESPR', 'IRWD', 'CGEN', 'AVNS', 'MYGN', 'AWH', 'TCRR',
                   'MODV', 'ARCT', 'EMBC', 'CVM', 'HCAT', 'INVA', 'NVAX', 'AORT',
                   'FLGT', 'USPH', 'RETA', 'CSII', 'MDRX', 'AERI', 'KDNY', 'SDGR',
                   'EBS', 'GRPH', 'VREX', 'VCEL', 'MD', 'CHRS', 'TVTX', 'NVTA',
                   'RGNX', 'KIDS', 'NRIX', 'INGN', 'TWST', 'VCYT', 'HIMS', 'ALEC',
                   'ZYNE', 'ALXO', 'BLUE', 'VXRT', 'BNGO', 'ZIMV', 'FATE', 'CDNA',
                   'ORMP', 'MRVI', 'LGND', 'ANIP', 'ENTA', 'ATRA', 'CLOV', 'LYEL',
                   'BTAI', 'DMTK', 'RYTM', 'KOD', 'AGIO', 'NEO', 'TSVT', 'ARQT', 
                   'SAVA', 'AVXL', 'DCPH', 'ALLO', 'FULC', 'ZNTL', 'OSUR', 'TRHC',
                   'RXRX', 'CARA', 'SLDB', 'EDIT', 'ARVN', 'INO', 'APLT', 'ICPT',
                   'IGMS', 'AFMD', 'BYSI', 'SWTX', 'IOVA', 'GTHX', 'ALLK', 'SGMO',
                   'HRTX', 'AVIR', 'PRAX', 'NKTR', 'ALT'
                  ]

tickers_techs = ['UPWK', 'APPS', 'NFLX', 'SNAP', 'ISRG', 'SQSP', 'ZG', 'BE',
                 'SEDG', 'WIX', 'FSLR', 'TSLA', 'SSTK', 'PSN', 'APP', 'BYND',
                 'ADBE', 'QRVO', 'JNPR', 'PINS', 'NVDA', 'PLTR', 'FISV', 'FSLY',
                 'RPD', 'NET', 'ANET', 'VMW', 'AEIS', 'TTD', 'AKAM', 'ORCL', 
                 'DOCN', 'FTNT', 'CRM', 'QLYS', 'V', 'SPLK', 'TTWO', 'ANSS',
                 'U', 'TDC', 'RKLB', 'PANW', 'PYPL', 'COUP', 'SONY', 'SNPS', 
                 'STX', 'DT', 'FORM', 'SWKS', 'SHOP', 'MA', 'ADSK', 'PLUG', 
                 'AZPN', 'AMD', 'SDGR', 'ZM', 'EPAM', 'ONTO', 'TREX', 'ABNB', 
                 'CRWD', 'BKI', 'LRCX', 'CGNX', 'MDB', 'INTC', 'NOW', 'ASGN', 
                 'PAYC', 'TWLO', 'PSA', 'APPN', 'DISH', 'BMBL', 'PTON', 'HOOD', 
                 'DLR', 'ROKU', 'GTLB', 'COIN', 'UPST', 'IT', 'ETSY', 'SPT', 
                 'PSTG', 'OKTA', 'ASAN', 'AAPL', 'MSFT', 'AMZN', 'PRGS', 'SQ',
                 'SNOW', 'ZS', 'HUBS', 'KEYS', 'AYX', 'TXN', 'DELL', 'GRMN',
                 'ADI', 'MU', 'CIEN', 'DIOD', 'QCOM', 'IBM', 'AMAT', 'DBX',
                 'RBLX', 'ESTC', 'MSTR', 'RIOT', 'AI'
                  ]

tickers_crypto = ['BTCUSD', 'ETHUSD', 'MATICUSD', 'LINKUSD', 'AVAXUSD', 'TONUSD',
                  'NEARUSD', 'STXUSD', 'FTMUSD', 'THETAUSD', 'C98USD', 'APTUSD',
                  'OPUSD', 'GMXUSD', 'TWTUSD', 'GLMRUSD', 'BLURUSD', 'LPTUSD',
                  'API3USD', 'GTCUSD', 'CFXUSD', 'GRTUSD0', 'DOGEUSD', 'LITUSD0',
                  'CHESSUSD', 'USDTUSD', 'BNBUSD', 'SOLUSD', 'DOTUSD', 'ATOMUSD',
                  'FILUSD', 'VETUSD', 'ALGOUSD', 'QNTUSD', 'EOSUSD', 'MANAUSD',
                  'XTZUSD', 'FLOWUSD', 'RPLUSD', 'CHZUSD', 'KLAYUSD', 'MASKUSD',
                  'KDAUSD', 'BANDUSD', 'CKBUSD', 'REEFUSD', 'STMXUSD', 'OOEUSD',
                  'ARUSD', 'BLZUSD', 'STORJUSD', 'DUSKUSD0', 'IOTXUSD', 'MAGICUSD',
                  'XRPUSD', 'KSMUSD', 'HIVEUSD', 'RLCUSD', 'LDOUSD0', 'NEOUSD',
                  'MDTUSD', 'MOVRUSD', 'FLUXUSD0', 'PHAUSD', 'AUDIOUSD', 'ELFUSD0',
                  'IMXUSD', 'CELOUSD', 'WAVESUSD', 'OCEANUSD', 'LQTYUSD', 'HNTUSD',
                  'TELUSD', 'SKLUSD', 'CELRUSD', 'CHRUSD', 'NFTUSD', 'REQUSD', 
                  'STEEMUSD'
                  ]

tickers_china = ['3888.HK', '0992.HK', '9868.HK', '1368.HK', '0700.HK', '0881.HK',
                 '2359.HK', '2020.HK', '1810.HK', '2518.HK', '9888.HK', '1929.HK',
                 '6618.HK', '2382.HK', '2333.HK', '0175.HK', '3690.HK', '1024.HK',
                 '2899.HK', '1997.HK', '9626.HK', '2313.HK', '0241.HK', '1171.HK',
                 '6969.HK', '9988.HK', '2238.HK', '2331.HK', '2015.HK', '9999.HK',
                 '0168.HK', '6881.HK', '1299.HK', '1919.HK', '9696.HK', '9618.HK',
                 '0388.HK', '3898.HK', '1044.HK', '0291.HK', '2269.HK', '0960.HK',
                 '0968.HK', '2319.HK', '2196.HK', '0016.HK', '1876.HK', '1066.HK',
                 '0836.HK', '6030.HK', '9633.HK', '2328.HK', '1347.HK', '0101.HK',
                 '2600.HK', '2202.HK', '1378.HK', '0788.HK', '3988.HK', '2007.HK',
                 '0027.HK', '0267.HK', '1288.HK', '6690.HK', '0688.HK', '0001.HK',
                 '1398.HK', '1113.HK', '1928.HK', '2388.HK', '0669.HK', '1038.HK',
                 '3968.HK', '2628.HK', '1177.HK', '0939.HK', '0868.HK', '1336.HK',
                 '0066.HK', '0012.HK', '6862.HK', '1109.HK', '0916.HK', '3908.HK',
                 '3800.HK', '0857.HK', '6185.HK', '6098.HK', '0003.HK', '0338.HK',
                 '0914.HK', '1385.HK', '1093.HK', '0386.HK', '0670.HK', '3692.HK',
                 '1061.HK', '2688.HK', '1099.HK', '2601.HK', '1898.HK', '2883.HK',
                 '1801.HK', '9995.HK', '0268.HK'
                ]

tickers_crypto_KuCoin = ['AERGO-USDT', 'AGIX-USDT', 'AKRO-USDT', 'API3-USDT', 'ARB-USDT', 'ARDR-USDT',
                         'ARK-USDT', 'AR-USDT', 'ASTR-USDT', 'ATOM-USDT', 'AUDIO-USDT', 'AVAX-USDT',
                         'BAND-USDT', 'BIFI-USDT', 'BLZ-USDT', 'BNB-USDT', 'BTC-USDT', 'C98-USDT',
                         'CFX-USDT', 'CHESS-USDT', 'CHR-USDT', 'CHZ-USDT', 'CKB-USDT', 'COS-USDT',
                         'CTSI-USDT', 'CTXC-USDT', 'DATA-USDT', 'DEXE-USDT', 'DF-USDT', 'DGB-USDT',
                         'DOGE-USDT', 'DOT-USDT', 'DUSK-USDT', 'ELF-USDT', 'EOS-USDT', 'ERN-USDT',
                         'ETH-USDT', 'FET-USDT', 'FIL-USDT', 'FLM-USDT', 'FLUX-USDT', 'FTM-USDT',
                         'FTT-USDT', 'GFT-USDT', 'GHST-USDT', 'GLM-USDT', 'GLMR-USDT', 'GMX-USDT',
                         'GRT-USDT', 'GTC-USDT', 'HARD-USDT', 'HIVE-USDT', 'ICP-USDT', 'ICX-USDT',
                         'IMX-USDT', 'IOTX-USDT', 'IQ-USDT', 'KDA-USDT', 'KEY-USDT', 'KSM-USDT',
                         'LDO-USDT', 'LINA-USDT', 'LINK-USDT', 'LIT-USDT', 'LIT-USDT', 'LOOM-USDT',
                         'LRC-USDT', 'LSK-USDT', 'MAGIC-USDT', 'MANA-USDT', 'MATIC-USDT', 'MBL-USDT',
                         'MINA-USDT', 'MOVR-USDT', 'NEAR-USDT', 'NEO-USDT', 'NKN-USDT', 'OCEAN-USDT', 
                         'ONE-USDT', 'OP-USDT', 'OXT-USDT', 'PHA-USDT', 'PHB-USDT', 'PLA-USDT',
                         'QI-USDT', 'QNT-USDT', 'QTUM-USDT', 'RAY-USDT', 'REEF-USDT', 'RLC-USDT',
                         'ROSE-USDT', 'RVN-USDT', 'SCRT-USDT', 'SNM-USDT', 'SOL-USDT', 'STEEM-USDT',
                         'STMX-USDT', 'STORJ-USDT', 'STPT-STX', 'T-USDT', 'THETA-USDT', 'TLM-USDT',
                         'TOMO-USDT', 'TRB-USDT', 'TWT-USDT', 'UTK-USDT', 'VET-USDT', 'VIDT-USDT',
                         'WNXM-USDT', 'XNO-USDT', 'XRP-USDT', 'XTZ-USDT', 'ACE-USDT', 'AIOZ-USDT',
                         'AKRO-USDT', 'AMB-USDT', 'ANT-USDT', 'AVA-USDT', 'BLUR-USDT', 'CEEK-USDT',
                         'CELR-USDT', 'CLV-USDT', 'CUDOS-USDT', 'DAPPT-USDT', 'DAPPX-USDT', 'DC-USDT',
                         'DSLA-USDT', 'EVER-USDT', 'FTG-USDT', 'GEEQ-USDT', 'GGG-USDT', 'GHX-USDT',
                         'GMEE-USDT', 'GRIN-USDT', 'HAPI-USDT', 'HNT-USDT', 'IOI-USDT', 'KAT-USDT',
                         'KOK-USDT', 'LAYER-USDT', 'LIKE-USDT', 'LOOKS-USDT', 'LPT-USDT', 'LYM-USDT',
                         'MAN-USDT', 'MELOS-USDT', 'MITX-USDT', 'MOOV-USDT', 'MTRG-USDT', 'MV-USDT',
                         'NAKA-USDT', 'NOIA-USDT', 'NUM-USDT', 'ONSTON-USDT', 'ONT-USDT', 'OOE-USDT',
                         'ORN-USDT', 'REN-USDT', 'RLY-USDT', 'RMRK-USDT', 'RNDR-USDT', 'SENSO-USDT', 
                         'SHA-USDT', 'SXP-USDT', 'TEL-USDT', 'TLOS-USDT', 'TRVL-USDT', 'TT-USDT',
                         'TVK-USDT', 'UOS-USDT', 'VISION-USDT', 'VXV-USDT', 'WILD-USDT', 'ZKT-USDT'
                        ]

tickers_energy = ['CLB', 'SU', 'WHD', 'PDCE', 'SHEL', 'VTS', 'LNG', 'MPC',
                 'TRGP', 'DK', 'PBA', 'VTNR', 'FANG', 'NOV', 'PBF', 'PDS',
                 'HAL', 'REX', 'HP', 'CCJ', 'PUMP', 'VAL', 'RRC', 'OGE',
                 'DVN', 'SLB', 'CNQ', 'VLO', 'COP', 'ENB', 'XOM', 'CVX', 
                 'OVV', 'NFE', 'EQT', 'CEG', 'TTE', 'SWN', 'EOG', 'HES',
                 'CNX', 'MRO', 'OXY', 'FTI', 'APA', 'MGY', 'ET', 'VET', 
                 'ARCH', 'SR', 'OII', 'AM', 'MUR', 'WMB', 'OIS', 'CTRA', 
                 'CHX', 'KMI', 'PXD', 'BKR', 'BE', 'ENPH', 'VST', 'UUUU', 
                 'SWX', 'OKE', 'AMR', 'PSX', 'WTTR', 'GEVO', 'OGS', 'BLDP', 
                 'ETRN', 'RIG', 'FCEL'
                  ]

tickers_indexes = ['XU100.IS', '^IBEX', '^IBEX', '^SSMI', '^TECDAX', '^GDAXI', '^IMOEX', '^STOXX',
                     '^RUI', '^FTMC', '^BVSP', '^N225', '^BFX', '^FTSE', '^NDX', '^NYA',
                     '^HSCE', '^NSEI', '^FCHI', '^HSI', '^CASE', '^IXIC', '^DJUSSC', '^DJU',
                     '^DJT', '^DJITR', '^GSPC', '^MID', '^FTLC', '^DJI'
                     'ETRN', 'RIG', 'FCEL'
                  ]

tickers_commodity = ['OUSX', 'FCUSX', 'ZGUSD', 'ZIUSD', 'KWUSX', 'SMUSD', 'SUSX', 'CUSX',
                     'LCUSX', 'BOUSX', 'LHUSX', 'RRUSD', 'PLUSD', 'ZCUSX', 'KEUSX', 'ZOUSX',
                     'NGUSD', 'ZSUSX', 'OJUSX', 'HGUSD', 'GCUSD', 'LBUSD', 'HOUSD', 'CCUSD',
                     'CLUSD', 'KCUSX', 'RBUSD', 'SIUSD', 'CTUSX', 'PAUSD'
                    ]